### PR TITLE
Add monitoring for extension and skins modifications (patch by @gitmapd)

### PR DESCRIPTION
**Pull request by yaronkoren**
His attempts to get this patch through kept failing due to 403 errors during validation, so we're seeing if I can get it through instead.

### CODE REVIEW

**Comment by yaronkoren** [comment]
Fixes #159.

**Review by jeffw16 — APPROVED** [review]
I have no comments, so I'll approve this with the proviso that I haven't personally tested this.

**Comment by vedmaka** [comment]
apparently this patch requires a follow up to be done in some future to support for extensions requiring either `update.php` script to be ran and/or having Composer dependencies

**Comment by jeffw16** [comment]
Why is it overkill to run `update.php` and `composer update` both each time?

**Comment by yaronkoren** [comment]
You're right that it might not be overkill at all - but on the other hand, thinking about it again now, I might have been correct, but for the wrong reason, that these calls should be avoided. The problem with update.php, if I'm thinking about it correctly, is not that it would be too costly to call, but that it actually wouldn't work at all: it will only make the relevant DB changes once the extension is enabled - but at the time this script runs, the extension has only been added, not enabled, so update.php will do nothing.

As for "composer update" - I don't know if it requires enabling the extension, but even if it does, the code could instead just go into the extension's directory and call "composer install", so that part is fine. However, it doesn't seem that useful: this would only be relevant for extensions that are installed via a two-step method (Git or download, then Composer), which I think is a relatively small number; and it would just save calling one command, which presumably the admin knows they need to call anyway, if they're following the installation instructions. Plus, maybe there's a chance that this extension requires calling something other than a plain "composer install" (or "composer install --no-dev"), so calling it automatically could potentially even mess up the installation. (I'm just speculating - maybe that's not possible.) Anyway, I think it would be only minimally useful.

**Comment by jeffw16** [comment]
Oh right, makes sense. Great points Yaron!

**Pull request merged**
