### PR TITLE
Add QuickInstantCommons extension

### LINKED ISSUE #238: Add Extension:QuickInstantCommons
QuickInstantCommons is a big improvement on MediaWiki's built-in Instant Commons feature. It is in use on Miraheze and is useful in general.

<https://www.mediawiki.org/wiki/Extension:QuickInstantCommons>

### PR DESCRIPTION
**Pull request by yaronkoren**
Fixes #238.

### CODE REVIEW

**Review by jeffw16 — APPROVED** [review]
Wow, I am so sorry for not approving this sooner! Approved.

**Comment by yaronkoren** [comment]
Thanks for approving this! Although probably this extension shouldn't be added until the MW 1.43 release of Canasta - I might have jumped the gun by creating this patch already.

**Comment by jeffw16** [comment]
Wait, shouldn't we merge this in regardless? What's the concern with waiting until 1.43?

**Comment by yaronkoren** [comment]
Closing - modifies the Dockerfile instead of the new YAML file.

**Pull request closed without merging**
