### PR TITLE
Update base to debian 11.7

### PR DESCRIPTION
**Pull request by bawolff**
Use the more up to date 11.7 as the base.

### CODE REVIEW

**Comment by yaronkoren** [comment]
Generally, the policy is only to do software updates alongside MediaWiki releases, for the sake of reliability/avoiding surprises - unless there's a bug that needs fixing, in which case of course the rules are different. Is there a specific reason to upgrade to Debian 11.7?

**Comment by tosfos** [comment]
It's due to vulnerabilities in 11.5. See [here](https://hub.docker.com/layers/library/debian/11.5/images/sha256-a4b14cf13428c71a5fce6d9380eb2ac1452a7ae4253e594dc90c8a884fdf3db2?context=explore) .

**Review by jeffw16 — APPROVED** [review]

**Comment by yaronkoren** [comment]
I'm not sure what the right answer is about updating Debian if there are no known issues, but a security vulnerability is definitely a good reason to upgrade.

**Comment by tosfos** [comment]
Thanks guys!

**Pull request merged**
